#!/usr/bin/env node

import { createInterface } from "readline";
import { execSync } from "child_process";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "fs";
import { resolve } from "path";
import { fileURLToPath } from "url";

const ROOT = resolve(fileURLToPath(import.meta.url), "..");
const SERVER_DIR = resolve(ROOT, "server");
const ENV_PATH = resolve(SERVER_DIR, ".env");
const ENV_EXAMPLE = resolve(SERVER_DIR, ".env.example");

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(query) {
  return new Promise((resolve) => rl.question(query, resolve));
}

function print(label, text) {
  console.log(`\n\x1b[36m${label}\x1b[0m`);
  console.log(text);
}

console.log(`
  ╔══════════════════════════════════════╗
  ║        nook-image-gpt  setup         ║
  ╚══════════════════════════════════════╝
`);

const key = await ask("? Enter your API Key: ");
const url = await ask("? Relay URL (Enter for default: https://sub.jarodfund.xyz): ");
const apiBase = url.trim() || "https://sub.jarodfund.xyz";

rl.close();

const envContent = `# Generated by setup.js
IMAGE_API_KEY=${key}
IMAGE_API_BASE=${apiBase}
`;

writeFileSync(ENV_PATH, envContent, "utf-8");
console.log("\n  ✓ .env created at server/.env");

console.log("\n  Installing dependencies...");
try {
  execSync("npm install", { cwd: SERVER_DIR, stdio: "inherit" });
} catch {
  console.error("  ✗ npm install failed");
  process.exit(1);
}

console.log("\n  Verifying server startup...");
try {
  const testInput = [
    JSON.stringify({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "setup", version: "1.0.0" } } }),
    JSON.stringify({ jsonrpc: "2.0", id: 2, method: "notifications/initialized", params: {} }),
    JSON.stringify({ jsonrpc: "2.0", id: 3, method: "tools/list" }),
  ].join("\n");

  const result = execSync(`node index.js`, {
    cwd: SERVER_DIR,
    input: testInput,
    encoding: "utf-8",
    env: { ...process.env, IMAGE_API_KEY: key, IMAGE_API_BASE: apiBase },
  });

  const lines = result.trim().split("\n");
  const listResponse = JSON.parse(lines[lines.length - 1]);
  if (listResponse?.result?.tools?.[0]?.name === "generate_image") {
    console.log("  ✓ Server started and generate_image tool detected");
  } else {
    throw new Error("Unexpected response");
  }
} catch (e) {
  console.error(`  ✗ Server verification failed: ${e.message}`);
  process.exit(1);
}

console.log("\n  ────────────────────────────────────────────");
console.log("  Setup complete! Add this to your agent config:");
console.log("  ────────────────────────────────────────────\n");

const absServerFile = resolve(SERVER_DIR, "index.js").replace(/\\/g, "\\\\");

print("opencode (opencode.json)", `{
  "mcp": {
    "nook-image-gpt": {
      "type": "local",
      "command": ["node", "${absServerFile}"],
      "enabled": true,
      "environment": {
        "IMAGE_API_KEY": "${key}",
        "IMAGE_API_BASE": "${apiBase}"
      }
    }
  }
}`);

print("Claude Code (claude.json / .mcp.json)", `{
  "mcpServers": {
    "nook-image-gpt": {
      "command": "node",
      "args": ["${absServerFile}"],
      "env": {
        "IMAGE_API_KEY": "${key}",
        "IMAGE_API_BASE": "${apiBase}"
      }
    }
  }
}`);

print("Cursor / Windsurf", `Command: node
Args: ${absServerFile}
Env: IMAGE_API_KEY=${key}, IMAGE_API_BASE=${apiBase}`);

console.log("\n  Key saved to server/.env. Your key will NOT be shown in git.\n");
